
Brute_Tankmech_Name = "Canon Taurus",
Brute_Tankmech_Description = "Tir un projectile puissant qui endommage et pousse sa cible.", 
Brute_Tankmech_Upgrade1 = "+1 Dommage",
Brute_Tankmech_Upgrade2 = "+1 Dommage",
Brute_Tankmech_A_Description = "Augmente les dommages de 1.",
Brute_Tankmech_B_Description = "Augmente les dommages de 1.",

Brute_Jetmech_Name = "Punition",
Brute_Jetmech_Description = "Vole au dessus d'une cible et lui largue une bombe fumigène explosive.", 
Brute_Jetmech_Upgrade1 = "+1 Dommage",
Brute_Jetmech_Upgrade2 = "+1 en portée",
Brute_Jetmech_A_Description = "Augmente les dommages de 1.",
Brute_Jetmech_B_Description = "Permet de sauter et d'attaquer une cible supplémentaire.",

Brute_Mirrorshot_Name = "Canon miroir",
Brute_Mirrorshot_Description = "Tire deux projectiles dans des directions opposées.", 
Brute_Mirrorshot_Upgrade1 = "+1 Dommage",
Brute_Mirrorshot_Upgrade2 = "+1 Dommage",
Brute_Mirrorshot_A_Description = "Augmente les dommages de 1.",
Brute_Mirrorshot_B_Description = "Augmente les dommages de 1.",

Brute_PhaseShot_Name = "Phase Canon",
Brute_PhaseShot_Description = "Tir un projectile qui traverse les objets.", 
Brute_PhaseShot_Upgrade1 = "+1 Dommage",
Brute_PhaseShot_Upgrade2 = "+1 Dommage",
Brute_PhaseShot_A_Description = "Augmente les dommages de 1.",
Brute_PhaseShot_B_Description = "Augmente les dommages de 1.",

Brute_Grapple_Name = "Grappin Crochet",
Brute_Grapple_Description = "Utilise un grappin pour attirer le Mech vers des objets ou des unités vers le Mech.", 
Brute_Grapple_Upgrade1 = "",
Brute_Grapple_Upgrade2 = "",
Brute_Grapple_A_Description = "",
Brute_Grapple_B_Description = "",

Brute_Shrapnel_Name = "Obus Défensif",
Brute_Shrapnel_Description = "Tir un projectile ne provoquant aucun dégât, poussant les tuiles autour de la cible.", 
Brute_Shrapnel_Upgrade1 = "",
Brute_Shrapnel_Upgrade2 = "",
Brute_Shrapnel_A_Description = "",
Brute_Shrapnel_B_Description = "",

Brute_Beetle_Name = "Moteurs Fracassants",
Brute_Beetle_Description = "Vol sur une ligne et s'écrase sur la cible, en la poussant et en vous blessant.", 
Brute_Beetle_Upgrade1 = "+1 Dommage à chacun",
Brute_Beetle_Upgrade2 = "Augmente les dommages de 1",
Brute_Beetle_A_Description = "Augmente les dommages auto-infligés et à la cible de 1.",
Brute_Beetle_B_Description = "Augmente les dommages de 1.",

Brute_Unstable_Name = "Canon Instable",
Brute_Unstable_Description = "Projectile puissant qui inflige des dégâts au tireur ainsi qu'à la cible.", 
Brute_Unstable_Upgrade1 = "+1 Dommage à chacun",
Brute_Unstable_Upgrade2 = "+1 Dommage",
Brute_Unstable_A_Description = "Augmente les dommages de 1 and increase self-damage by 1.",
Brute_Unstable_B_Description = "Augmente les dommages de 1.",

Brute_Heavyrocket_Name = "Roquette Dévastatrice",
Brute_Heavyrocket_Description = "Tire une roquette qui endommage fortement une cible et pousse les tuiles adjacentes.", 
Brute_Heavyrocket_Upgrade1 = "+1 Utilisation",
Brute_Heavyrocket_Upgrade2 = "+2 Dommages",
Brute_Heavyrocket_A_Description = "Augmente le nombre d'utilisation de 1.",
Brute_Heavyrocket_B_Description = "Augmente les dommages de 2.",

Brute_Splitshot_Name = "Tir coupé",
Brute_Splitshot_Description = "Tire un projectile qui endommage et pousse la tuile ciblée ainsi que les tuiles à sa gauche et à droite.", 
Brute_Splitshot_Upgrade1 = "+1 Utilisation",
Brute_Splitshot_Upgrade2 = "+1 Dommage",
Brute_Splitshot_A_Description = "Augmente le nombre d'utilisation de 1.",
Brute_Splitshot_B_Description = "Augmente les dommages de 2.",

_Name = "",
_Description = "", 
_Upgrade1 = "",
_Upgrade2 = "",
_A_Description = "",
_B_Description = "",

_Name = "",
_Description = "", 
_Upgrade1 = "",
_Upgrade2 = "",
_A_Description = "",
_B_Description = "",

_Name = "",
_Description = "", 
_Upgrade1 = "",
_Upgrade2 = "",
_A_Description = "",
_B_Description = "",

_Name = "",
_Description = "", 
_Upgrade1 = "",
_Upgrade2 = "",
_A_Description = "",
_B_Description = "",

_Name = "",
_Description = "", 
_Upgrade1 = "",
_Upgrade2 = "",
_A_Description = "",
_B_Description = "",

_Name = "",
_Description = "", 
_Upgrade1 = "",
_Upgrade2 = "",
_A_Description = "",
_B_Description = "",

_Name = "",
_Description = "", 
_Upgrade1 = "",
_Upgrade2 = "",
_A_Description = "",
_B_Description = "",

